name: Build Pebble APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Install EAS CLI
      run: npm install -g eas-cli
      
    - name: Login to EAS
      run: eas login --non-interactive
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        
    - name: Build APK
      run: eas build --platform android --profile production --non-interactive
      
    - name: Download APK
      run: |
        # Get the latest build
        BUILD_ID=$(eas build:list --platform=android --status=finished --limit=1 --json | jq -r '.[0].id')
        echo "Downloading build $BUILD_ID"
        eas build:download --id=$BUILD_ID
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: pebble-apk
        path: "*.apk"
        retention-days: 30
